# .github/workflows/github-pages.yml
name: Deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main  # or whatever your default branch is

permissions:
  contents: write

jobs:
  github-pages:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2' # or whatever version works with your theme

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Build site
      run: JEKYLL_ENV=production bundle exec jekyll build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
